# Generated by Django 2.1.2 on 2018-10-22 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(blank=True, max_length=100, null=True)),
                ('car_link', models.CharField(blank=True, max_length=100, null=True)),
                ('car_photo', models.CharField(blank=True, max_length=300, null=True)),
                ('car_year', models.CharField(blank=True, max_length=100, null=True)),
                ('car_type', models.CharField(blank=True, max_length=100, null=True)),
                ('car_engine', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('car_brand', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsViewer.CarBrand'),
        ),
    ]
